### ISSUE TITLE
Incorrectly adds spaces after links (and other inline markup) at the end of sentences.

### ISSUE THREAD

**Issue by arlobelshee** [jonschlinkert/pretty#2]
This transforms the original text:

A <a href="whatever">simple example</a>.

to:

A <a href="whatever">simple example</a> .

Which changes the rendering from:

A <a href="whatever">simple example</a>.

to:

A <a href="whatever">simple example</a> .

The problem is the last replace expression in your ocd function. However, I am not sure what problem that is working around. I think you need to find and fix the underlying problem so that you don't need the workaround.

Until then, I've simply disabled prettification. I would much rather have messy and overly-long HTML that renders correctly.

**Comment by jonschlinkert** [comment]
thanks for creating the issue. I'll look into it. 

> I would much rather have messy and overly-long HTML that renders correctly.

well, I would hope so lol. we all would. I never use prettification in production code, I just prefer looking at structured HTML during dev. not to digress, the code in the project is old, and I would do it differently today.

**Comment by george-norris-salesforce** [comment]
Any update on this?

**Comment by jonschlinkert** [comment]
hi @george-norris-salesforce, thanks for the ping. I'll pull it down now

**Comment by jonschlinkert** [comment]
@george-norris-salesforce I just pushed up 2.0. This is basically a thin wrapper around js-beautify to provide sensible defaults.
