### ISSUE TITLE
about the command "node i -d && mocha"

### ISSUE THREAD

**Issue by liuweifly** [jonschlinkert/pretty#3]
Hi, when I use this command "node i -d && mocha", found a problem as following
![image](https://cloud.githubusercontent.com/assets/9208751/6778193/9a0d9f5c-d18b-11e4-8b61-bdb88456759b.png)
I have bad knowledge about "node". Can you help me find out a solution? 
3Q~

**Comment by jonschlinkert** [comment]
thanks for pointing this out. it should be:

```js
npm i -d && mocha
```
